---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
date: "`r format(Sys.time(), '%d %B, %Y')`"
---


## Loading and preprocessing the data
```{R setup, echo = TRUE, warning = FALSE}
library(knitr)
library(ggplot2)
library(lattice)

filename = "../data/activity.csv"
data = read.csv(filename, sep = ",")
```

We see that there are three variables, 'steps', 'date' and 'interval'. We have 17568 observations in total but there are also 2305 NA's under the 'steps' column. The maximum number of steps taken in a single interval is 806 and the minimum is 0. Moreover we have data of 61 days with 288 intervals a day.

```{R exploring data, echo = TRUE}
str(data)
summary(data)
```

## What is mean total number of steps taken per day?  

```{R Total steps per day, echo = TRUE}
# Ignore missing values
data_no_NA <- data[complete.cases(data),]
# 1. calculate total number of steps per day
total_steps <- aggregate(steps ~ date, data_no_NA, sum)
# 2. Make a histogram of the total number of steps taken each day
ggplot(total_steps, aes(x = steps)) + 
       geom_histogram(fill = "blue", binwidth = 1000) + 
        labs(title="Histogram of Steps Taken per Day", 
             x = "Number of Steps per Day", y = "Number of times in a day(Count)")
```
     
The mean of the total number of steps per day is:
``` {R mean of s, echo = TRUE}
# mean of total steps per day
mean(total_steps$steps)
```

The median of the total number of steps per day is:
``` {R median of s, echo = TRUE}
# median of total steps per day
median(total_steps$steps)
```

## What is the average daily activity pattern?
```{R Daily activity, echo = TRUE}
# 1. Make a time series plot of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
average_steps <- aggregate(steps ~ interval, data_no_NA, mean)
plot(average_steps, type = "l", xlab = "Interval", ylab = "Average steps")
```

The interval with the maximum average steps across all days is: 
``` {R maximum average per interval, echo = TRUE}
#2. Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
average_steps[average_steps$steps == max(average_steps$steps), 1]
```

## Imputing missing values
The total number of rows with missing values is:
``` {R Total number of row with missing values, echo = TRUE}
#1. Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)
nrow(data[!complete.cases(data),])
```

Replace all missing values with the average value of that interval.
``` {R Replace NAs, echo = TRUE}
# 2.Fill in all of the missing values in the dataset by using the mean value for that interval.
# merge original data with the average steps per interval data frame
data_temp <- merge(data, average_steps, by = 'interval', all.y = F)
data_temp$steps.x[is.na(data_temp$steps.x)] <- round(data_temp$steps.y[is.na(data_temp$steps.x)])
#3. Create a new dataset that is equal to the original dataset but with the missing data filled in.
data_replaced_NA <- data_temp[, 1:3]
colnames(data_replaced_NA) <- c("interval", "steps", "date")
```

Calculate again the mean and median of the total steps taken per day.
``` {R total steps per day new, echo = TRUE}
total_steps_new <- aggregate(steps ~ date, data_replaced_NA, sum)
# 2. Make a histogram of the total number of steps taken each day
ggplot(total_steps_new, aes(x = steps)) + 
       geom_histogram(fill = "blue", binwidth = 1000) + 
        labs(title="Histogram of Steps Taken per Day", 
             x = "Number of Steps per Day", y = "Number of times in a day(Count)")
```
     
The mean of the total number of steps per day is:
``` {R mean of s new, echo = TRUE}
# mean of total steps per day
mean(total_steps_new$steps)
```

The median of the total number of steps per day is:
``` {R median of s new, echo = TRUE}
# median of total steps per day
median(total_steps_new$steps)
```

Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?

The new mean and median values do not significantly differ from the values calculated with data where the missing values where ignored. This is explained by the fact that we used a mean value calculated with th rest of the data to replace the missing values.

## Are there differences in activity patterns between weekdays and weekends?
``` {R extra column weekday, echo = TRUE}
#1. Create a new factor variable in the dataset with two levels - "weekday" and "weekend" indicating whether a given date is a weekday or weekend day.
data_replaced_NA$date <- as.Date(data_replaced_NA$date)
data_replaced_NA$day <- "weekday"
data_replaced_NA$day[weekdays(data_replaced_NA$date, abb=T) %in% c("Sat","Sun")] <- "weekend"
data_replaced_NA$day <- as.factor(data_replaced_NA$day)
```

Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). 
``` {R Make a panel plot containing a time series plot, echo = TRUE}
#2. Make a panel plot containing a time series plot
average_steps_day <- aggregate(steps ~ interval + day, data_replaced_NA, mean)
xyplot(steps ~ interval | day, average_steps_day, type="l", grid=T, layout=c(1,2), ylab="Number of steps", xlab="interval")
```

From the plot made in de code chunk here above it can be seen that there are differences between weekdays and weekends. During the weekend there are more steps taken during the day while on weekdays the most steps are taking in the beginning of the day.